"""Init

Revision ID: ad22a86d4fec
Revises: 0875867825c6
Create Date: 2023-10-17 20:16:04.725667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad22a86d4fec'
down_revision: Union[str, None] = '0875867825c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'line_items', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_items', type_='unique')
    # ### end Alembic commands ###
