from crud.crud_academic_session import crud_academicsession
from crud.crud_category import crud_category
from crud.crud_class import crud_class
from crud.crud_classresource import crud_classresource
from crud.crud_course import crud_course
from crud.crud_courseresource import crud_courseresource
from crud.crud_demographic import crud_demographic
from crud.crud_enrollment import crud_enrollment
from crud.crud_lineitem import crud_lineitem
from crud.crud_org import crud_org
from crud.crud_resource import crud_resource
from crud.crud_result import crud_result
from crud.crud_user import crud_user
