"""Initial tables

Revision ID: 84ac5581e001
Revises: 6f11197b911d
Create Date: 2023-12-27 22:02:24.123482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ac5581e001'
down_revision: Union[str, None] = '6f11197b911d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sourcedId', sa.String(255), nullable=False),
    sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    sa.Column('dateLastModified', sa.String(255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Department', 'School', 'District', 'Local', 'State', 'National', name='orgtype'), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('parentSourcedId', sa.String(255), nullable=True),
    sa.ForeignKeyConstraint(['parentSourcedId'], ['org.sourcedId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sourcedId')
    )
    # op.create_table('category',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('resource',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('vendorResourceId', sa.String(length=255), nullable=False),
    # sa.Column('title', sa.String(length=255), nullable=True),
    # sa.Column('roles', sa.ARRAY(sa.Enum('Administrator', 'Aide', 'Guardian', 'Parent', 'Proctor', 'Relative', 'Student', 'Teacher', name='roletype')), nullable=True),
    # sa.Column('importance', sa.Enum('Primary', 'Secondary', name='importance'), nullable=True),
    # sa.Column('vendorId', sa.String(length=255), nullable=True),
    # sa.Column('applicationId', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId'),
    # sa.UniqueConstraint('vendorResourceId')
    # )
    # op.create_table('user',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('enabledUser', sa.Enum('TRUE', 'FALSE', name='truefalse'), nullable=False),
    # sa.Column('orgSourcedIds', sa.ARRAY(sa.String(255)), nullable=False),
    # sa.Column('role', sa.Enum('Administrator', 'Aide', 'Guardian', 'Parent', 'Proctor', 'Relative', 'Student', 'Teacher', name='roletype'), nullable=False),
    # sa.Column('username', sa.String(length=255), nullable=False),
    # sa.Column('userIds', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('givenName', sa.String(length=255), nullable=False),
    # sa.Column('familyName', sa.String(length=255), nullable=False),
    # sa.Column('middleName', sa.String(length=255), nullable=True),
    # sa.Column('identifier', sa.String(length=255), nullable=True),
    # sa.Column('email', sa.String(length=255), nullable=True),
    # sa.Column('sms', sa.String(length=255), nullable=True),
    # sa.Column('phone', sa.String(length=255), nullable=True),
    # sa.Column('agentSourcedIds', sa.ARRAY(sa.String(255)), nullable=True),
    # sa.Column('grades', sa.String(length=255), nullable=True),
    # sa.Column('password', sa.String(length=255), nullable=True),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('academic_session',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('type', sa.Enum('GradingPeriod', 'Semester', 'SchoolYear', 'Term', name='sessiontype'), nullable=False),
    # sa.Column('startDate', sa.Date(), nullable=False),
    # sa.Column('endDate', sa.Date(), nullable=False),
    # sa.Column('parentSourcedId', sa.String(255), nullable=True),
    # sa.Column('schoolYear', sa.Integer(), nullable=False),
    # sa.Column('schoolSourcedId', sa.String(255), nullable=False),
    # sa.ForeignKeyConstraint(['parentSourcedId'], ['academic_session.sourcedId'], ),
    # sa.ForeignKeyConstraint(['schoolSourcedId'], ['org.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('course',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('schoolYearSourcedId', sa.String(255), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('courseCode', sa.String(length=255), nullable=True),
    # sa.Column('grades', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('orgSourcedId', sa.String(255), nullable=False),
    # sa.Column('subjects', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('subjectCodes', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.ForeignKeyConstraint(['orgSourcedId'], ['org.sourcedId'], ),
    # sa.ForeignKeyConstraint(['schoolYearSourcedId'], ['academic_session.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('class',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('grades', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('courseSourcedId', sa.String(255), nullable=False),
    # sa.Column('classCode', sa.String(length=255), nullable=True),
    # sa.Column('classType', sa.Enum('Homeroom', 'Scheduled', name='classtype'), nullable=False),
    # sa.Column('location', sa.String(length=255), nullable=True),
    # sa.Column('schoolSourcedId', sa.String(255), nullable=False),
    # sa.Column('termSourcedIds', sa.ARRAY(sa.String(255)), nullable=False),
    # sa.Column('subjects', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('subjectCodes', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.Column('periods', sa.ARRAY(sa.String(length=255)), nullable=True),
    # sa.ForeignKeyConstraint(['courseSourcedId'], ['course.sourcedId'], ),
    # sa.ForeignKeyConstraint(['schoolSourcedId'], ['org.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('course_resource',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=True),
    # sa.Column('courseSourcedId', sa.String(255), nullable=False),
    # sa.Column('resourceSourcedId', sa.String(255), nullable=False),
    # sa.ForeignKeyConstraint(['courseSourcedId'], ['course.sourcedId'], ),
    # sa.ForeignKeyConstraint(['resourceSourcedId'], ['resource.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('class_resource',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=True),
    # sa.Column('classSourcedId', sa.String(255), nullable=False),
    # sa.Column('resourceSourcedId', sa.String(255), nullable=False),
    # sa.ForeignKeyConstraint(['classSourcedId'], ['class.sourcedId'], ),
    # sa.ForeignKeyConstraint(['resourceSourcedId'], ['resource.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('enrollment',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('classSourcedId', sa.String(255), nullable=False),
    # sa.Column('schoolSourcedId', sa.String(255), nullable=False),
    # sa.Column('userSourcedId', sa.String(255), nullable=False),
    # sa.Column('role', sa.Enum('Administrator', 'Aide', 'Guardian', 'Parent', 'Proctor', 'Relative', 'Student', 'Teacher', name='roletype'), nullable=False),
    # sa.Column('primary', sa.Enum('TRUE', 'FALSE', name='truefalse'), nullable=True),
    # sa.Column('beginDate', sa.Date(), nullable=True),
    # sa.Column('endDate', sa.Date(), nullable=True),
    # sa.ForeignKeyConstraint(['classSourcedId'], ['class.sourcedId'], ),
    # sa.ForeignKeyConstraint(['schoolSourcedId'], ['org.sourcedId'], ),
    # sa.ForeignKeyConstraint(['userSourcedId'], ['user.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('line_item',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.String(length=255), nullable=True),
    # sa.Column('assignDate', sa.Date(), nullable=False),
    # sa.Column('dueDate', sa.Date(), nullable=False),
    # sa.Column('classSourcedId', sa.String(255), nullable=False),
    # sa.Column('categorySourcedId', sa.String(255), nullable=False),
    # sa.Column('gradingPeriodSourcedId', sa.String(255), nullable=False),
    # sa.Column('resultValueMin', sa.Float(), nullable=False),
    # sa.Column('resultValueMax', sa.Float(), nullable=False),
    # sa.ForeignKeyConstraint(['categorySourcedId'], ['category.sourcedId'], ),
    # sa.ForeignKeyConstraint(['classSourcedId'], ['class.sourcedId'], ),
    # sa.ForeignKeyConstraint(['gradingPeriodSourcedId'], ['academic_session.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # op.create_table('result',
    # sa.Column('sourcedId', sa.String(255), nullable=False),
    # sa.Column('status', sa.Enum('Active', 'ToBeDeleted', 'Inactive', name='status'), nullable=True),
    # sa.Column('dateLastModified', sa.DateTime(), nullable=True),
    # sa.Column('lineItemSourcedId', sa.String(255), nullable=False),
    # sa.Column('studentSourcedId', sa.String(255), nullable=False),
    # sa.Column('scoreStatus', sa.Enum('Exempt', 'FullyGraded', 'NotSubmitted', 'PartiallyGraded', 'Submitted', name='scorestatus'), nullable=False),
    # sa.Column('score', sa.Float(), nullable=False),
    # sa.Column('scoreDate', sa.Date(), nullable=False),
    # sa.Column('comment', sa.String(length=255), nullable=True),
    # sa.ForeignKeyConstraint(['lineItemSourcedId'], ['line_item.sourcedId'], ),
    # sa.ForeignKeyConstraint(['studentSourcedId'], ['user.sourcedId'], ),
    # sa.PrimaryKeyConstraint('sourcedId'),
    # sa.UniqueConstraint('sourcedId')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('line_item')
    op.drop_table('enrollment')
    op.drop_table('class_resource')
    op.drop_table('course_resource')
    op.drop_table('class')
    op.drop_table('course')
    op.drop_table('academic_session')
    op.drop_table('user')
    op.drop_table('resource')
    op.drop_table('org')
    op.drop_table('category')
    # ### end Alembic commands ###
