"""Init

Revision ID: 5709e868f08b
Revises: 3a9a9b2d7859
Create Date: 2023-10-15 23:30:56.257753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5709e868f08b'
down_revision: Union[str, None] = '3a9a9b2d7859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classes', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='unique')
    # ### end Alembic commands ###
