"""Init

Revision ID: 8ed8f3edc174
Revises: 5709e868f08b
Create Date: 2023-10-15 23:47:45.487629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed8f3edc174'
down_revision: Union[str, None] = '5709e868f08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classResources', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classResources', type_='unique')
    # ### end Alembic commands ###
