"""Init

Revision ID: 9c300e1f04d6
Revises: ad22a86d4fec
Create Date: 2023-10-17 20:23:46.078079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c300e1f04d6'
down_revision: Union[str, None] = 'ad22a86d4fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.create_unique_constraint(None, 'orgs', ['sourcedId'])
    op.create_unique_constraint(None, 'resources', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    op.drop_constraint(None, 'orgs', type_='unique')
    op.create_table('results',
    sa.Column('sourcedId', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'tobedeleted', 'inactive', name='enum_status'), autoincrement=False, nullable=False),
    sa.Column('dateLastModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lineItemSourcedId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('studentSourcedId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scoreStatus', postgresql.ENUM('enumeration_values_for_scoreStatus', name='enum_scoreStatus'), autoincrement=False, nullable=False),
    sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('scoreDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sourcedId', name='results_pkey')
    )
    # ### end Alembic commands ###
