"""Init

Revision ID: efc25e694e71
Revises: 9c300e1f04d6
Create Date: 2023-10-17 20:24:44.392479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc25e694e71'
down_revision: Union[str, None] = '9c300e1f04d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'results', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='unique')
    # ### end Alembic commands ###
