"""Init

Revision ID: fc1b8c12ecc5
Revises: 8ce4a02a41c6
Create Date: 2023-10-16 20:50:50.433134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc1b8c12ecc5'
down_revision: Union[str, None] = '8ce4a02a41c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('sourcedId', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'tobedeleted', 'inactive', name='enum_status'), autoincrement=False, nullable=False),
    sa.Column('dateLastModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('classSourcedId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schoolSourcedId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userSourcedId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('administrator', 'proctor', 'student', 'teacher', name='enum_role'), autoincrement=False, nullable=True),
    sa.Column('primary', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('beginDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sourcedId', 'primary', name='enrollments_pkey'),
    sa.UniqueConstraint('primary', name='enrollments_primary_key'),
    sa.UniqueConstraint('sourcedId', name='enrollments_sourcedId_key')
    )
    # ### end Alembic commands ###
