import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SiteNavigationBar from "@/components/app/SiteNavigationBar";
import { AuthenticatedState } from "@/utils/models/auth"
import Footer from "@/components/app/SiteFooter";

interface AuthenticatedRouteContext {
  auth: AuthenticatedState
  navigationKey: string
  queryKey: string
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isAuthenticated = true;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteNavigationBar loggedIn={isAuthenticated} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
