# Run the local server.
local:
	make -C scripts dev

# Execute the latest database migrations.
migrate:
	make -C scripts migrate

# Initialize database with example data.
init:
	make -C scripts init

# Run all tests.
test:
	make -C tests all

# Run test coverage.
coverage:
	make -C tests coverage


