"""initialize_db

Revision ID: 17d0e3ea6f78
Revises: 
Create Date: 2024-09-02 04:03:14.261773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17d0e3ea6f78'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the schools table
    op.create_table(
        'schools',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('school_code', sa.String, unique=True, nullable=False),
        sa.Column('school_name', sa.String, nullable=False),
        sa.Column('address', sa.String, nullable=True),
        sa.Column('city', sa.String, nullable=True),
        sa.Column('state', sa.String, nullable=True),
        sa.Column('zip_code', sa.String, nullable=True),
        sa.Column('BDDemo', postgresql.JSONB, nullable=True)
    )

    # Create the people table
    op.create_table(
        'people',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('Firstname', sa.String, index=True),
        sa.Column('Lastname', sa.String, index=True),
        sa.Column('role', sa.Enum('administrator', 'aide', 'guardian', 'parent', 'proctor', 'relative', 'student', 'teacher', name='roleenum'), nullable=False, index=True),
        sa.Column('sourcedid', sa.String, unique=True, nullable=False, index=True),
        sa.Column('EnabledUser', sa.String, index=True),
        sa.Column('DateLastModified', sa.String, index=True),
        sa.Column('school_code', sa.String, sa.ForeignKey('schools.school_code'), nullable=True, index=True),
    )

    # Create the students table
    op.create_table(
        'students',
        sa.Column('id', sa.Integer, sa.ForeignKey('people.id'), primary_key=True, index=True),
        sa.Column('AnonymizedStudentID', sa.String, unique=True, nullable=False),
        sa.Column('AnonymizedStudentNumber', sa.String, nullable=True),
        sa.Column('BDDemo', postgresql.JSONB, nullable=True),
        sa.Column('role', sa.Enum('administrator', 'aide', 'guardian', 'parent', 'proctor', 'relative', 'student', 'teacher', name='roleenum'), nullable=False, index=True),
        sa.Column('sourcedid', sa.String, unique=True, nullable=False, index=True),
        sa.Column('Sections', sa.String, nullable=True),
        sa.Column('SchlAssociated', sa.String, nullable=True),
    )

    # Create the teachers table
    op.create_table(
        'teachers',
        sa.Column('id', sa.Integer, sa.ForeignKey('people.id'), primary_key=True, index=True),
        sa.Column('AnonymizedTeacherID', sa.String, unique=True, nullable=False),
        sa.Column('AnonymizedTeacherNumber', sa.String, nullable=True),
        sa.Column('Sections', sa.String, nullable=True),
        sa.Column('StuAssociated', postgresql.JSONB, nullable=True),
        sa.Column('SchlAssociated', sa.String, nullable=True),
        sa.Column('Credentials', sa.String, nullable=True),
        sa.Column('Subjects', sa.String, nullable=True),
        sa.Column('SiteDuties', sa.String, nullable=True),
        sa.Column('GradeLevels', sa.String, nullable=True),
        sa.Column('BDDemo', postgresql.JSONB, nullable=True),
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the teachers table
    op.drop_table('teachers')

    # Drop the students table
    op.drop_table('students')

    # Drop the people table
    op.drop_table('people')

    # Drop the schools table
    op.drop_table('schools')

    # ### end Alembic commands ###
