version: '3.8'

services:
  # PostgreSQL Database
  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}  # corrected variable name from ${DB_Name} to ${DB_NAME}

  # pgAdmin for managing the PostgreSQL Database
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}

  # Python Application
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis-stack
      - redis-stack-server

  # Redis Stack with RedisInsight
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6380:6379"  # Redis on port 6380 externally, 6379 internally
      - "8001:8001"  # RedisInsight on port 8001

  # Redis Stack Server without RedisInsight
  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"  # Redis on port 6379
