"""Initial tables

Revision ID: 0c5840d8c70b
Revises: fde56185afbd
Create Date: 2023-12-30 01:15:53.042499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5840d8c70b'
down_revision: Union[str, None] = 'fde56185afbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'academic_session', ['sourcedId'])
    op.create_unique_constraint(None, 'category', ['sourcedId'])
    op.create_unique_constraint(None, 'class', ['sourcedId'])
    op.create_unique_constraint(None, 'class_resource', ['sourcedId'])
    op.create_unique_constraint(None, 'course', ['sourcedId'])
    op.create_unique_constraint(None, 'course_resource', ['sourcedId'])
    op.create_unique_constraint(None, 'enrollment', ['sourcedId'])
    op.create_unique_constraint(None, 'line_item', ['sourcedId'])
    op.create_unique_constraint(None, 'org', ['sourcedId'])
    op.create_unique_constraint(None, 'resource', ['sourcedId'])
    op.create_unique_constraint(None, 'result', ['sourcedId'])
    op.create_unique_constraint(None, 'user', ['sourcedId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'result', type_='unique')
    op.drop_constraint(None, 'resource', type_='unique')
    op.drop_constraint(None, 'org', type_='unique')
    op.drop_constraint(None, 'line_item', type_='unique')
    op.drop_constraint(None, 'enrollment', type_='unique')
    op.drop_constraint(None, 'course_resource', type_='unique')
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_constraint(None, 'class_resource', type_='unique')
    op.drop_constraint(None, 'class', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'academic_session', type_='unique')
    # ### end Alembic commands ###
